# Generated by Django 3.1.2 on 2020-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', 'Select a title'), ('female', 'female'), ('male', 'male')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('', 'Select a title'), ('entry', 'entry'), ('junior', 'junior'), ('manager', 'manager'), ('mid', 'mid'), ('senior', 'senior')], default='', max_length=7),
        ),
    ]
