# Generated by Django 3.1.2 on 2020-10-13 09:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rootapp', '0003_auto_20201012_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',), 'verbose_name': 'Employee Detail'},
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(choices=[('', 'Select a title'), ('CON', 'Consumables'), ('EXP', 'Expenses'), ('PRO', 'Promotion'), ('SUP', 'Support')], default='', max_length=3),
        ),
    ]
