# Generated by Django 3.1.2 on 2020-10-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0004_auto_20201013_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
