# Generated by Django 3.1.2 on 2020-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0005_report_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
